import type { SalesMenuProduct } from './types';

export const initialSalesMenu: SalesMenuProduct[] = [
  {
    id: 'menu-hamburguesa-simple',
    name: 'Hamburguesa Simple',
    category: 'Comidas',
    station: 'Parrilla',
    price: 5200,
    emoji: '🍔',
    active: true,
    recipe: [
      { stockProductId: 'p11', quantity: 1 },
      { stockProductId: 'p12', quantity: 1 },
      { stockProductId: 'p13', quantity: 1 },
    ],
  },
  {
    id: 'menu-hamburguesa-completa',
    name: 'Hamburguesa Completa',
    category: 'Comidas',
    station: 'Parrilla',
    price: 6900,
    emoji: '🍔',
    active: true,
    recipe: [
      { stockProductId: 'p11', quantity: 1 },
      { stockProductId: 'p12', quantity: 1 },
      { stockProductId: 'p13', quantity: 2 },
    ],
  },
  {
    id: 'menu-pancho',
    name: 'Pancho',
    category: 'Comidas',
    station: 'Cocina',
    price: 3500,
    emoji: '🌭',
    active: true,
    recipe: [
      { stockProductId: 'p5', quantity: 1 },
      { stockProductId: 'p6', quantity: 1 },
    ],
  },
  {
    id: 'menu-coca',
    name: 'Coca-Cola 500ml',
    category: 'Bebidas',
    station: 'Barra',
    price: 2900,
    emoji: '🥤',
    active: true,
    recipe: [{ stockProductId: 'p1', quantity: 1 }],
  },
  {
    id: 'menu-agua',
    name: 'Agua Mineral 500ml',
    category: 'Bebidas',
    station: 'Barra',
    price: 2200,
    emoji: '💧',
    active: true,
    recipe: [{ stockProductId: 'p2', quantity: 1 }],
  },
  {
    id: 'menu-cerveza',
    name: 'Cerveza Quilmes Lata',
    category: 'Bebidas',
    station: 'Barra',
    price: 3700,
    emoji: '🍺',
    active: true,
    recipe: [{ stockProductId: 'p3', quantity: 1 }],
  },
  {
    id: 'menu-papas',
    name: 'Papas Fritas Grandes',
    category: 'Snacks',
    station: 'Cocina',
    price: 4100,
    emoji: '🍟',
    active: true,
    recipe: [{ stockProductId: 'p4', quantity: 1 }],
  },
  {
    id: 'menu-combo-cantina',
    name: 'Combo Cantina',
    category: 'Promos',
    station: 'Cocina',
    price: 9900,
    emoji: '🎯',
    active: true,
    recipe: [
      { stockProductId: 'p5', quantity: 1 },
      { stockProductId: 'p6', quantity: 1 },
      { stockProductId: 'p1', quantity: 2 },
    ],
  },
];

export const salesMenuTabs = [
  { key: 'inicio', label: 'Inicio' },
  { key: 'mostrador', label: 'Mostrador' },
  { key: 'pedidos', label: 'Mis Pedidos' },
  { key: 'devoluciones', label: 'Devoluciones' },
  { key: 'productos', label: 'Productos' },
  { key: 'mesas', label: 'Mesas' },
  { key: 'metricas', label: 'Métricas' },
  { key: 'reportes', label: 'Reportes' },
  { key: 'historial', label: 'Historial' },
  { key: 'ajustes', label: 'Ajustes' },
] as const;
