/** Claves de localStorage — no renombrar sin migración de datos en clientes. */
export const storageKeys = {
  inventory: {
    products: 'stock-products',
    warehouses: 'stock-warehouses',
    orders: 'stock-orders',
    auditLog: 'stock-auditlog',
    categories: 'stock-categories',
    consumption: 'stock-consumption',
    employeeConsumption: 'stock-employee-consumption',
    movements: 'stock-movements',
    countSessions: 'stock-count-sessions',
    suppliers: 'stock-suppliers',
    darkMode: 'stock-darkmode',
    alertDay: 'stock-alert-day',
    currentUser: 'stock-current-user',
    users: 'stock-users',
    lowStockNotifications: 'stock-low-notifications',
    autoAlerts: 'stock-auto-alerts',
    packRounding: 'stock-pack-rounding',
  },
  platform: {
    notificationsEnabled: 'platform-notifications',
    notificationSound: 'platform-notification-sound',
  },
  sales: {
    categories: 'sales-categories',
    categoryEmojis: 'sales-category-emojis',
    kitchens: 'sales-kitchens',
    products: 'sales-products',
    tickets: 'sales-tickets',
    ticketCounter: 'sales-ticket-counter',
    tables: 'sales-tables',
    history: 'sales-history',
    auditLog: 'sales-auditlog',
    printers: 'sales-printers',
    ticketTemplate: 'sales-ticket-template',
    validateStockOnSale: 'sales-validate-stock',
    raceConditionProtection: 'sales-race-protection',
  },
  futbol: {
    showPublicFixture: 'futbol-public-fixture',
    matchNotifications: 'futbol-match-notifications',
    defaultCategory: 'futbol-default-category',
  },
  kitchen: {
    orders: 'kitchen-orders',
  },
  online: {
    products: 'online-products',
    sponsors: 'sponsors',
    media: 'media-items',
    orderNotifications: 'online-order-notifications',
    syncCatalogWithStock: 'online-sync-catalog',
    webChannelEnabled: 'online-web-channel',
    appChannelEnabled: 'online-app-channel',
  },
} as const;
